[build]
  publish = "."
  command = ""

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Force HTTPS
[[redirects]]
  from = "http://slotenmakeramsterdamwest.amsterdam/*"
  to = "https://slotenmakeramsterdamwest.amsterdam/:splat"
  status = 301
  force = true

# Block public access to old path
[[redirects]]
  from = "/opdrachtbon"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/opdrachtbon/*"
  to = "/404.html"
  status = 404
  force = true

## Secret page moved to separate project; remove special handling here
